spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:8080
  boot:
    admin:
      client:
        url: http://localhost:2000

server:
  port: 5000

eureka:
  instance:
    hostname: api-gateway-5000
  client:
    service-url:
      defaultZone: http://eureka-server-7000:7000/eureka

zuul:
  routes:
    api-feign:
      path: /api/feign/**
      serviceId: consumer-service-feign
    api-ribbon:
      path: /api/ribbon/**
      serviceId: consumer-service-ribbon


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS